/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PhaseStatus = IDL.Variant({
  'completed' : IDL.Null,
  'planned' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Phase = IDL.Record({
  'status' : PhaseStatus,
  'releaseId' : IDL.Text,
  'phaseGoal' : IDL.Text,
  'targetDate' : IDL.Text,
  'phaseName' : IDL.Text,
  'phaseId' : IDL.Text,
});
export const ReleaseStatus = IDL.Variant({
  'released' : IDL.Null,
  'planned' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Release = IDL.Record({
  'status' : ReleaseStatus,
  'releaseId' : IDL.Text,
  'targetDate' : IDL.Text,
  'releaseGoal' : IDL.Text,
  'releaseName' : IDL.Text,
});
export const UseCaseStatus = IDL.Variant({
  'done' : IDL.Null,
  'test' : IDL.Null,
  'inBuild' : IDL.Null,
  'approved' : IDL.Null,
  'proposed' : IDL.Null,
  'deferred' : IDL.Null,
});
export const UseCaseValue = IDL.Variant({
  'low' : IDL.Null,
  'med' : IDL.Null,
  'high' : IDL.Null,
});
export const Time = IDL.Int;
export const UseCaseEffort = IDL.Variant({
  'l' : IDL.Null,
  'm' : IDL.Null,
  's' : IDL.Null,
});
export const UseCasePriority = IDL.Variant({
  'p0' : IDL.Null,
  'p1' : IDL.Null,
  'p2' : IDL.Null,
  'p3' : IDL.Null,
});
export const UseCase = IDL.Record({
  'status' : UseCaseStatus,
  'title' : IDL.Text,
  'value' : UseCaseValue,
  'owner' : IDL.Text,
  'tags' : IDL.Text,
  'ucId' : IDL.Text,
  'lastUpdated' : Time,
  'createdDate' : Time,
  'description' : IDL.Text,
  'effort' : UseCaseEffort,
  'mvpReleaseId' : IDL.Text,
  'priority' : UseCasePriority,
  'phaseId' : IDL.Text,
});
export const MVPRelease = IDL.Record({
  'useCases' : IDL.Vec(UseCase),
  'releases' : IDL.Vec(Release),
  'phases' : IDL.Vec(Phase),
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const AppConfig = IDL.Record({
  'version' : IDL.Text,
  'adminPasscode' : IDL.Text,
  'isReleased' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changePhaseRelease' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'changeUseCasePhase' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createPhase' : IDL.Func([Phase], [], []),
  'createRelease' : IDL.Func([Release], [], []),
  'createUseCase' : IDL.Func([UseCase], [IDL.Text], []),
  'deletePhase' : IDL.Func([IDL.Text], [], []),
  'deleteRelease' : IDL.Func([IDL.Text], [], []),
  'deleteUseCase' : IDL.Func([IDL.Text], [], []),
  'filterUseCasesByPhase' : IDL.Func([IDL.Text], [IDL.Vec(UseCase)], ['query']),
  'filterUseCasesByPriority' : IDL.Func(
      [UseCasePriority],
      [IDL.Vec(UseCase)],
      ['query'],
    ),
  'filterUseCasesByRelease' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UseCase)],
      ['query'],
    ),
  'filterUseCasesByStatus' : IDL.Func(
      [UseCaseStatus],
      [IDL.Vec(UseCase)],
      ['query'],
    ),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllMVPReleases' : IDL.Func([], [MVPRelease], ['query']),
  'getAllPhases' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
  'getAllUseCases' : IDL.Func([], [IDL.Vec(UseCase)], ['query']),
  'getAppConfig' : IDL.Func([], [AppConfig], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getPhase' : IDL.Func([IDL.Text], [Phase], ['query']),
  'getPhasesByReleaseId' : IDL.Func([IDL.Text], [IDL.Vec(Phase)], ['query']),
  'getRelease' : IDL.Func([IDL.Text], [Release], ['query']),
  'getUseCase' : IDL.Func([IDL.Text], [UseCase], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAppConfig' : IDL.Func([AppConfig], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sortPhasesByStatus' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
  'sortReleasesByStatus' : IDL.Func([], [IDL.Vec(Release)], ['query']),
  'sortUseCasesByLastUpdated' : IDL.Func([], [IDL.Vec(UseCase)], ['query']),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updateAppConfig' : IDL.Func([AppConfig], [], []),
  'updatePhase' : IDL.Func([Phase], [], []),
  'updateRelease' : IDL.Func([Release], [], []),
  'updateUseCase' : IDL.Func([UseCase], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PhaseStatus = IDL.Variant({
    'completed' : IDL.Null,
    'planned' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Phase = IDL.Record({
    'status' : PhaseStatus,
    'releaseId' : IDL.Text,
    'phaseGoal' : IDL.Text,
    'targetDate' : IDL.Text,
    'phaseName' : IDL.Text,
    'phaseId' : IDL.Text,
  });
  const ReleaseStatus = IDL.Variant({
    'released' : IDL.Null,
    'planned' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Release = IDL.Record({
    'status' : ReleaseStatus,
    'releaseId' : IDL.Text,
    'targetDate' : IDL.Text,
    'releaseGoal' : IDL.Text,
    'releaseName' : IDL.Text,
  });
  const UseCaseStatus = IDL.Variant({
    'done' : IDL.Null,
    'test' : IDL.Null,
    'inBuild' : IDL.Null,
    'approved' : IDL.Null,
    'proposed' : IDL.Null,
    'deferred' : IDL.Null,
  });
  const UseCaseValue = IDL.Variant({
    'low' : IDL.Null,
    'med' : IDL.Null,
    'high' : IDL.Null,
  });
  const Time = IDL.Int;
  const UseCaseEffort = IDL.Variant({
    'l' : IDL.Null,
    'm' : IDL.Null,
    's' : IDL.Null,
  });
  const UseCasePriority = IDL.Variant({
    'p0' : IDL.Null,
    'p1' : IDL.Null,
    'p2' : IDL.Null,
    'p3' : IDL.Null,
  });
  const UseCase = IDL.Record({
    'status' : UseCaseStatus,
    'title' : IDL.Text,
    'value' : UseCaseValue,
    'owner' : IDL.Text,
    'tags' : IDL.Text,
    'ucId' : IDL.Text,
    'lastUpdated' : Time,
    'createdDate' : Time,
    'description' : IDL.Text,
    'effort' : UseCaseEffort,
    'mvpReleaseId' : IDL.Text,
    'priority' : UseCasePriority,
    'phaseId' : IDL.Text,
  });
  const MVPRelease = IDL.Record({
    'useCases' : IDL.Vec(UseCase),
    'releases' : IDL.Vec(Release),
    'phases' : IDL.Vec(Phase),
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const AppConfig = IDL.Record({
    'version' : IDL.Text,
    'adminPasscode' : IDL.Text,
    'isReleased' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changePhaseRelease' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'changeUseCasePhase' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createPhase' : IDL.Func([Phase], [], []),
    'createRelease' : IDL.Func([Release], [], []),
    'createUseCase' : IDL.Func([UseCase], [IDL.Text], []),
    'deletePhase' : IDL.Func([IDL.Text], [], []),
    'deleteRelease' : IDL.Func([IDL.Text], [], []),
    'deleteUseCase' : IDL.Func([IDL.Text], [], []),
    'filterUseCasesByPhase' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UseCase)],
        ['query'],
      ),
    'filterUseCasesByPriority' : IDL.Func(
        [UseCasePriority],
        [IDL.Vec(UseCase)],
        ['query'],
      ),
    'filterUseCasesByRelease' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UseCase)],
        ['query'],
      ),
    'filterUseCasesByStatus' : IDL.Func(
        [UseCaseStatus],
        [IDL.Vec(UseCase)],
        ['query'],
      ),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllMVPReleases' : IDL.Func([], [MVPRelease], ['query']),
    'getAllPhases' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllReleases' : IDL.Func([], [IDL.Vec(Release)], ['query']),
    'getAllUseCases' : IDL.Func([], [IDL.Vec(UseCase)], ['query']),
    'getAppConfig' : IDL.Func([], [AppConfig], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getPhase' : IDL.Func([IDL.Text], [Phase], ['query']),
    'getPhasesByReleaseId' : IDL.Func([IDL.Text], [IDL.Vec(Phase)], ['query']),
    'getRelease' : IDL.Func([IDL.Text], [Release], ['query']),
    'getUseCase' : IDL.Func([IDL.Text], [UseCase], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAppConfig' : IDL.Func([AppConfig], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sortPhasesByStatus' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
    'sortReleasesByStatus' : IDL.Func([], [IDL.Vec(Release)], ['query']),
    'sortUseCasesByLastUpdated' : IDL.Func([], [IDL.Vec(UseCase)], ['query']),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updateAppConfig' : IDL.Func([AppConfig], [], []),
    'updatePhase' : IDL.Func([Phase], [], []),
    'updateRelease' : IDL.Func([Release], [], []),
    'updateUseCase' : IDL.Func([UseCase], [], []),
  });
};

export const init = ({ IDL }) => { return []; };