/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppConfig {
  'version' : string,
  'adminPasscode' : string,
  'isReleased' : boolean,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface MVPRelease {
  'useCases' : Array<UseCase>,
  'releases' : Array<Release>,
  'phases' : Array<Phase>,
}
export interface Phase {
  'status' : PhaseStatus,
  'releaseId' : string,
  'phaseGoal' : string,
  'targetDate' : string,
  'phaseName' : string,
  'phaseId' : string,
}
export type PhaseStatus = { 'completed' : null } |
  { 'planned' : null } |
  { 'inProgress' : null };
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Release {
  'status' : ReleaseStatus,
  'releaseId' : string,
  'targetDate' : string,
  'releaseGoal' : string,
  'releaseName' : string,
}
export type ReleaseStatus = { 'released' : null } |
  { 'planned' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UseCase {
  'status' : UseCaseStatus,
  'title' : string,
  'value' : UseCaseValue,
  'owner' : string,
  'tags' : string,
  'ucId' : string,
  'lastUpdated' : Time,
  'createdDate' : Time,
  'description' : string,
  'effort' : UseCaseEffort,
  'mvpReleaseId' : string,
  'priority' : UseCasePriority,
  'phaseId' : string,
}
export type UseCaseEffort = { 'l' : null } |
  { 'm' : null } |
  { 's' : null };
export type UseCasePriority = { 'p0' : null } |
  { 'p1' : null } |
  { 'p2' : null } |
  { 'p3' : null };
export type UseCaseStatus = { 'done' : null } |
  { 'test' : null } |
  { 'inBuild' : null } |
  { 'approved' : null } |
  { 'proposed' : null } |
  { 'deferred' : null };
export type UseCaseValue = { 'low' : null } |
  { 'med' : null } |
  { 'high' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changePhaseRelease' : ActorMethod<[string, string], undefined>,
  'changeUseCasePhase' : ActorMethod<[string, string], undefined>,
  'createPhase' : ActorMethod<[Phase], undefined>,
  'createRelease' : ActorMethod<[Release], undefined>,
  'createUseCase' : ActorMethod<[UseCase], string>,
  'deletePhase' : ActorMethod<[string], undefined>,
  'deleteRelease' : ActorMethod<[string], undefined>,
  'deleteUseCase' : ActorMethod<[string], undefined>,
  'filterUseCasesByPhase' : ActorMethod<[string], Array<UseCase>>,
  'filterUseCasesByPriority' : ActorMethod<[UseCasePriority], Array<UseCase>>,
  'filterUseCasesByRelease' : ActorMethod<[string], Array<UseCase>>,
  'filterUseCasesByStatus' : ActorMethod<[UseCaseStatus], Array<UseCase>>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllMVPReleases' : ActorMethod<[], MVPRelease>,
  'getAllPhases' : ActorMethod<[], Array<Phase>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllReleases' : ActorMethod<[], Array<Release>>,
  'getAllUseCases' : ActorMethod<[], Array<UseCase>>,
  'getAppConfig' : ActorMethod<[], AppConfig>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getPhase' : ActorMethod<[string], Phase>,
  'getPhasesByReleaseId' : ActorMethod<[string], Array<Phase>>,
  'getRelease' : ActorMethod<[string], Release>,
  'getUseCase' : ActorMethod<[string], UseCase>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAppConfig' : ActorMethod<[AppConfig], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sortPhasesByStatus' : ActorMethod<[], Array<Phase>>,
  'sortReleasesByStatus' : ActorMethod<[], Array<Release>>,
  'sortUseCasesByLastUpdated' : ActorMethod<[], Array<UseCase>>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateAppConfig' : ActorMethod<[AppConfig], undefined>,
  'updatePhase' : ActorMethod<[Phase], undefined>,
  'updateRelease' : ActorMethod<[Release], undefined>,
  'updateUseCase' : ActorMethod<[UseCase], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];