/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface AppConfig {
    version: string;
    adminPasscode: string;
    isReleased: boolean;
}
export interface MVPRelease {
    useCases: Array<UseCase>;
    releases: Array<Release>;
    phases: Array<Phase>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UseCase {
    status: UseCaseStatus;
    title: string;
    value: UseCaseValue;
    owner: string;
    tags: string;
    ucId: string;
    lastUpdated: Time;
    createdDate: Time;
    description: string;
    effort: UseCaseEffort;
    mvpReleaseId: string;
    priority: UseCasePriority;
    phaseId: string;
}
export interface Phase {
    status: PhaseStatus;
    releaseId: string;
    phaseGoal: string;
    targetDate: string;
    phaseName: string;
    phaseId: string;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface Release {
    status: ReleaseStatus;
    releaseId: string;
    targetDate: string;
    releaseGoal: string;
    releaseName: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum PhaseStatus {
    completed = "completed",
    planned = "planned",
    inProgress = "inProgress"
}
export enum ReleaseStatus {
    released = "released",
    planned = "planned",
    inProgress = "inProgress"
}
export enum UseCaseEffort {
    l = "l",
    m = "m",
    s = "s"
}
export enum UseCasePriority {
    p0 = "p0",
    p1 = "p1",
    p2 = "p2",
    p3 = "p3"
}
export enum UseCaseStatus {
    done = "done",
    test = "test",
    inBuild = "inBuild",
    approved = "approved",
    proposed = "proposed",
    deferred = "deferred"
}
export enum UseCaseValue {
    low = "low",
    med = "med",
    high = "high"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changePhaseRelease(phaseId: string, newReleaseId: string): Promise<void>;
    changeUseCasePhase(ucId: string, newPhaseId: string): Promise<void>;
    createPhase(phase: Phase): Promise<void>;
    createRelease(release: Release): Promise<void>;
    createUseCase(uc: UseCase): Promise<string>;
    deletePhase(id: string): Promise<void>;
    deleteRelease(id: string): Promise<void>;
    deleteUseCase(id: string): Promise<void>;
    filterUseCasesByPhase(phaseId: string): Promise<Array<UseCase>>;
    filterUseCasesByPriority(priority: UseCasePriority): Promise<Array<UseCase>>;
    filterUseCasesByRelease(releaseId: string): Promise<Array<UseCase>>;
    filterUseCasesByStatus(status: UseCaseStatus): Promise<Array<UseCase>>;
    generateInviteCode(): Promise<string>;
    getAllMVPReleases(): Promise<MVPRelease>;
    getAllPhases(): Promise<Array<Phase>>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getAllReleases(): Promise<Array<Release>>;
    getAllUseCases(): Promise<Array<UseCase>>;
    getAppConfig(): Promise<AppConfig>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getPhase(id: string): Promise<Phase>;
    getPhasesByReleaseId(releaseId: string): Promise<Array<Phase>>;
    getRelease(id: string): Promise<Release>;
    getUseCase(id: string): Promise<UseCase>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAppConfig(config: AppConfig): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sortPhasesByStatus(): Promise<Array<Phase>>;
    sortReleasesByStatus(): Promise<Array<Release>>;
    sortUseCasesByLastUpdated(): Promise<Array<UseCase>>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    updateAppConfig(config: AppConfig): Promise<void>;
    updatePhase(phase: Phase): Promise<void>;
    updateRelease(release: Release): Promise<void>;
    updateUseCase(uc: UseCase): Promise<void>;
}
import type { MVPRelease as _MVPRelease, Phase as _Phase, PhaseStatus as _PhaseStatus, Release as _Release, ReleaseStatus as _ReleaseStatus, Time as _Time, UseCase as _UseCase, UseCaseEffort as _UseCaseEffort, UseCasePriority as _UseCasePriority, UseCaseStatus as _UseCaseStatus, UseCaseValue as _UseCaseValue, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changePhaseRelease(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changePhaseRelease(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePhaseRelease(arg0, arg1);
            return result;
        }
    }
    async changeUseCasePhase(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeUseCasePhase(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeUseCasePhase(arg0, arg1);
            return result;
        }
    }
    async createPhase(arg0: Phase): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPhase(to_candid_Phase_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPhase(to_candid_Phase_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createRelease(arg0: Release): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRelease(to_candid_Release_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRelease(to_candid_Release_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createUseCase(arg0: UseCase): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createUseCase(to_candid_UseCase_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUseCase(to_candid_UseCase_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deletePhase(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhase(arg0);
            return result;
        }
    }
    async deleteRelease(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRelease(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRelease(arg0);
            return result;
        }
    }
    async deleteUseCase(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUseCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUseCase(arg0);
            return result;
        }
    }
    async filterUseCasesByPhase(arg0: string): Promise<Array<UseCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterUseCasesByPhase(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterUseCasesByPhase(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterUseCasesByPriority(arg0: UseCasePriority): Promise<Array<UseCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterUseCasesByPriority(to_candid_UseCasePriority_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterUseCasesByPriority(to_candid_UseCasePriority_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterUseCasesByRelease(arg0: string): Promise<Array<UseCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterUseCasesByRelease(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterUseCasesByRelease(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterUseCasesByStatus(arg0: UseCaseStatus): Promise<Array<UseCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterUseCasesByStatus(to_candid_UseCaseStatus_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterUseCasesByStatus(to_candid_UseCaseStatus_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAllMVPReleases(): Promise<MVPRelease> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMVPReleases();
                return from_candid_MVPRelease_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMVPReleases();
            return from_candid_MVPRelease_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPhases(): Promise<Array<Phase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPhases();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPhases();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getAllReleases(): Promise<Array<Release>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReleases();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReleases();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUseCases(): Promise<Array<UseCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUseCases();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUseCases();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppConfig(): Promise<AppConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppConfig();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getPhase(arg0: string): Promise<Phase> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhase(arg0);
                return from_candid_Phase_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhase(arg0);
            return from_candid_Phase_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhasesByReleaseId(arg0: string): Promise<Array<Phase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhasesByReleaseId(arg0);
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhasesByReleaseId(arg0);
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRelease(arg0: string): Promise<Release> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelease(arg0);
                return from_candid_Release_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelease(arg0);
            return from_candid_Release_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUseCase(arg0: string): Promise<UseCase> {
        if (this.processError) {
            try {
                const result = await this.actor.getUseCase(arg0);
                return from_candid_UseCase_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUseCase(arg0);
            return from_candid_UseCase_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAppConfig(arg0: AppConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAppConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAppConfig(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sortPhasesByStatus(): Promise<Array<Phase>> {
        if (this.processError) {
            try {
                const result = await this.actor.sortPhasesByStatus();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sortPhasesByStatus();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async sortReleasesByStatus(): Promise<Array<Release>> {
        if (this.processError) {
            try {
                const result = await this.actor.sortReleasesByStatus();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sortReleasesByStatus();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async sortUseCasesByLastUpdated(): Promise<Array<UseCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.sortUseCasesByLastUpdated();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sortUseCasesByLastUpdated();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAppConfig(arg0: AppConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppConfig(arg0);
            return result;
        }
    }
    async updatePhase(arg0: Phase): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePhase(to_candid_Phase_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePhase(to_candid_Phase_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRelease(arg0: Release): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRelease(to_candid_Release_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRelease(to_candid_Release_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUseCase(arg0: UseCase): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUseCase(to_candid_UseCase_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUseCase(to_candid_UseCase_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_MVPRelease_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MVPRelease): MVPRelease {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_PhaseStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PhaseStatus): PhaseStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Phase_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Phase): Phase {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_ReleaseStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReleaseStatus): ReleaseStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Release_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Release): Release {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UseCaseEffort_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UseCaseEffort): UseCaseEffort {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UseCasePriority_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UseCasePriority): UseCasePriority {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UseCaseStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UseCaseStatus): UseCaseStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UseCaseValue_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UseCaseValue): UseCaseValue {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UseCase_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UseCase): UseCase {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UseCaseStatus;
    title: string;
    value: _UseCaseValue;
    owner: string;
    tags: string;
    ucId: string;
    lastUpdated: _Time;
    createdDate: _Time;
    description: string;
    effort: _UseCaseEffort;
    mvpReleaseId: string;
    priority: _UseCasePriority;
    phaseId: string;
}): {
    status: UseCaseStatus;
    title: string;
    value: UseCaseValue;
    owner: string;
    tags: string;
    ucId: string;
    lastUpdated: Time;
    createdDate: Time;
    description: string;
    effort: UseCaseEffort;
    mvpReleaseId: string;
    priority: UseCasePriority;
    phaseId: string;
} {
    return {
        status: from_candid_UseCaseStatus_n31(_uploadFile, _downloadFile, value.status),
        title: value.title,
        value: from_candid_UseCaseValue_n33(_uploadFile, _downloadFile, value.value),
        owner: value.owner,
        tags: value.tags,
        ucId: value.ucId,
        lastUpdated: value.lastUpdated,
        createdDate: value.createdDate,
        description: value.description,
        effort: from_candid_UseCaseEffort_n35(_uploadFile, _downloadFile, value.effort),
        mvpReleaseId: value.mvpReleaseId,
        priority: from_candid_UseCasePriority_n37(_uploadFile, _downloadFile, value.priority),
        phaseId: value.phaseId
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    useCases: Array<_UseCase>;
    releases: Array<_Release>;
    phases: Array<_Phase>;
}): {
    useCases: Array<UseCase>;
    releases: Array<Release>;
    phases: Array<Phase>;
} {
    return {
        useCases: from_candid_vec_n28(_uploadFile, _downloadFile, value.useCases),
        releases: from_candid_vec_n41(_uploadFile, _downloadFile, value.releases),
        phases: from_candid_vec_n46(_uploadFile, _downloadFile, value.phases)
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ReleaseStatus;
    releaseId: string;
    targetDate: string;
    releaseGoal: string;
    releaseName: string;
}): {
    status: ReleaseStatus;
    releaseId: string;
    targetDate: string;
    releaseGoal: string;
    releaseName: string;
} {
    return {
        status: from_candid_ReleaseStatus_n44(_uploadFile, _downloadFile, value.status),
        releaseId: value.releaseId,
        targetDate: value.targetDate,
        releaseGoal: value.releaseGoal,
        releaseName: value.releaseName
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PhaseStatus;
    releaseId: string;
    phaseGoal: string;
    targetDate: string;
    phaseName: string;
    phaseId: string;
}): {
    status: PhaseStatus;
    releaseId: string;
    phaseGoal: string;
    targetDate: string;
    phaseName: string;
    phaseId: string;
} {
    return {
        status: from_candid_PhaseStatus_n49(_uploadFile, _downloadFile, value.status),
        releaseId: value.releaseId,
        phaseGoal: value.phaseGoal,
        targetDate: value.targetDate,
        phaseName: value.phaseName,
        phaseId: value.phaseId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    done: null;
} | {
    test: null;
} | {
    inBuild: null;
} | {
    approved: null;
} | {
    proposed: null;
} | {
    deferred: null;
}): UseCaseStatus {
    return "done" in value ? UseCaseStatus.done : "test" in value ? UseCaseStatus.test : "inBuild" in value ? UseCaseStatus.inBuild : "approved" in value ? UseCaseStatus.approved : "proposed" in value ? UseCaseStatus.proposed : "deferred" in value ? UseCaseStatus.deferred : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    med: null;
} | {
    high: null;
}): UseCaseValue {
    return "low" in value ? UseCaseValue.low : "med" in value ? UseCaseValue.med : "high" in value ? UseCaseValue.high : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    l: null;
} | {
    m: null;
} | {
    s: null;
}): UseCaseEffort {
    return "l" in value ? UseCaseEffort.l : "m" in value ? UseCaseEffort.m : "s" in value ? UseCaseEffort.s : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    p0: null;
} | {
    p1: null;
} | {
    p2: null;
} | {
    p3: null;
}): UseCasePriority {
    return "p0" in value ? UseCasePriority.p0 : "p1" in value ? UseCasePriority.p1 : "p2" in value ? UseCasePriority.p2 : "p3" in value ? UseCasePriority.p3 : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    released: null;
} | {
    planned: null;
} | {
    inProgress: null;
}): ReleaseStatus {
    return "released" in value ? ReleaseStatus.released : "planned" in value ? ReleaseStatus.planned : "inProgress" in value ? ReleaseStatus.inProgress : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    planned: null;
} | {
    inProgress: null;
}): PhaseStatus {
    return "completed" in value ? PhaseStatus.completed : "planned" in value ? PhaseStatus.planned : "inProgress" in value ? PhaseStatus.inProgress : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UseCase>): Array<UseCase> {
    return value.map((x)=>from_candid_UseCase_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Release>): Array<Release> {
    return value.map((x)=>from_candid_Release_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Phase>): Array<Phase> {
    return value.map((x)=>from_candid_Phase_n47(_uploadFile, _downloadFile, x));
}
function to_candid_PhaseStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhaseStatus): _PhaseStatus {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Phase_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Phase): _Phase {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ReleaseStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReleaseStatus): _ReleaseStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Release_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Release): _Release {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UseCaseEffort_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UseCaseEffort): _UseCaseEffort {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UseCasePriority_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UseCasePriority): _UseCasePriority {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UseCaseStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UseCaseStatus): _UseCaseStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UseCaseValue_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UseCaseValue): _UseCaseValue {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UseCase_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UseCase): _UseCase {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: PhaseStatus;
    releaseId: string;
    phaseGoal: string;
    targetDate: string;
    phaseName: string;
    phaseId: string;
}): {
    status: _PhaseStatus;
    releaseId: string;
    phaseGoal: string;
    targetDate: string;
    phaseName: string;
    phaseId: string;
} {
    return {
        status: to_candid_PhaseStatus_n12(_uploadFile, _downloadFile, value.status),
        releaseId: value.releaseId,
        phaseGoal: value.phaseGoal,
        targetDate: value.targetDate,
        phaseName: value.phaseName,
        phaseId: value.phaseId
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ReleaseStatus;
    releaseId: string;
    targetDate: string;
    releaseGoal: string;
    releaseName: string;
}): {
    status: _ReleaseStatus;
    releaseId: string;
    targetDate: string;
    releaseGoal: string;
    releaseName: string;
} {
    return {
        status: to_candid_ReleaseStatus_n16(_uploadFile, _downloadFile, value.status),
        releaseId: value.releaseId,
        targetDate: value.targetDate,
        releaseGoal: value.releaseGoal,
        releaseName: value.releaseName
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: UseCaseStatus;
    title: string;
    value: UseCaseValue;
    owner: string;
    tags: string;
    ucId: string;
    lastUpdated: Time;
    createdDate: Time;
    description: string;
    effort: UseCaseEffort;
    mvpReleaseId: string;
    priority: UseCasePriority;
    phaseId: string;
}): {
    status: _UseCaseStatus;
    title: string;
    value: _UseCaseValue;
    owner: string;
    tags: string;
    ucId: string;
    lastUpdated: _Time;
    createdDate: _Time;
    description: string;
    effort: _UseCaseEffort;
    mvpReleaseId: string;
    priority: _UseCasePriority;
    phaseId: string;
} {
    return {
        status: to_candid_UseCaseStatus_n20(_uploadFile, _downloadFile, value.status),
        title: value.title,
        value: to_candid_UseCaseValue_n22(_uploadFile, _downloadFile, value.value),
        owner: value.owner,
        tags: value.tags,
        ucId: value.ucId,
        lastUpdated: value.lastUpdated,
        createdDate: value.createdDate,
        description: value.description,
        effort: to_candid_UseCaseEffort_n24(_uploadFile, _downloadFile, value.effort),
        mvpReleaseId: value.mvpReleaseId,
        priority: to_candid_UseCasePriority_n26(_uploadFile, _downloadFile, value.priority),
        phaseId: value.phaseId
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhaseStatus): {
    completed: null;
} | {
    planned: null;
} | {
    inProgress: null;
} {
    return value == PhaseStatus.completed ? {
        completed: null
    } : value == PhaseStatus.planned ? {
        planned: null
    } : value == PhaseStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReleaseStatus): {
    released: null;
} | {
    planned: null;
} | {
    inProgress: null;
} {
    return value == ReleaseStatus.released ? {
        released: null
    } : value == ReleaseStatus.planned ? {
        planned: null
    } : value == ReleaseStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UseCaseStatus): {
    done: null;
} | {
    test: null;
} | {
    inBuild: null;
} | {
    approved: null;
} | {
    proposed: null;
} | {
    deferred: null;
} {
    return value == UseCaseStatus.done ? {
        done: null
    } : value == UseCaseStatus.test ? {
        test: null
    } : value == UseCaseStatus.inBuild ? {
        inBuild: null
    } : value == UseCaseStatus.approved ? {
        approved: null
    } : value == UseCaseStatus.proposed ? {
        proposed: null
    } : value == UseCaseStatus.deferred ? {
        deferred: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UseCaseValue): {
    low: null;
} | {
    med: null;
} | {
    high: null;
} {
    return value == UseCaseValue.low ? {
        low: null
    } : value == UseCaseValue.med ? {
        med: null
    } : value == UseCaseValue.high ? {
        high: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UseCaseEffort): {
    l: null;
} | {
    m: null;
} | {
    s: null;
} {
    return value == UseCaseEffort.l ? {
        l: null
    } : value == UseCaseEffort.m ? {
        m: null
    } : value == UseCaseEffort.s ? {
        s: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UseCasePriority): {
    p0: null;
} | {
    p1: null;
} | {
    p2: null;
} | {
    p3: null;
} {
    return value == UseCasePriority.p0 ? {
        p0: null
    } : value == UseCasePriority.p1 ? {
        p1: null
    } : value == UseCasePriority.p2 ? {
        p2: null
    } : value == UseCasePriority.p3 ? {
        p3: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
